version: '3.7'
services:
  app:
    build: ./app
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - "${LOG_PATH}:/var/log/app"
    environment:
      - FLASK_PORT=${FLASK_PORT}
      - LOG_PATH=/var/log/app

  elasticsearch:
    image: elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "${ELASTICSEARCH_PORT}:9200"

  kibana:
    image: kibana:7.17.10
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: ./elk
    depends_on:
      - elasticsearch
    volumes:
      - ./logs:/var/log/app:ro

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    environment:
      - FLASK_PORT=${FLASK_PORT}

  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
