version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.17.10
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build: .
    depends_on:
      - elasticsearch
    volumes:
      - ../logs:/var/log/app:ro

