strict.perms: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app/app.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:${KIBANA_PORT}"
